-- Insert sample products for Royal Foods - Indian Breads Specialist
-- Note: Run this after insert-royalfoods-store.sql and insert-royalfoods-categories.sql

-- Insert sample products for each bread category
INSERT INTO public.products (
  megha_store_id,
  sku,
  name,
  price,
  rating,
  review_count,
  serves,
  description,
  image_url,
  customisable,
  category,
  tags,
  discount_percentage,
  old_price,
  preparation_time,
  is_available,
  is_featured,
  sort_order,
  created_at,
  updated_at
) VALUES 
-- Chapati Products
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-CHP-001',
  'Plain Chapati',
  15.00,
  4.6,
  234,
  1,
  'Soft whole wheat flatbread made fresh on tawa',
  'assets/images/royalfoods/products/1.png',
  false,
  'Chapati',
  '["vegetarian", "wheat", "healthy", "fresh"]'::jsonb,
  0,
  null,
  5,
  true,
  true,
  1,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-CHP-002',
  'Butter Chapati',
  20.00,
  4.7,
  345,
  1,
  'Soft chapati brushed with fresh butter',
  'assets/images/royalfoods/products/2.png',
  false,
  'Chapati',
  '["vegetarian", "wheat", "butter", "popular"]'::jsonb,
  10,
  22.00,
  5,
  true,
  true,
  2,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-CHP-003',
  'Ghee Chapati',
  25.00,
  4.8,
  456,
  1,
  'Traditional chapati with pure ghee',
  'assets/images/royalfoods/products/3.png',
  false,
  'Chapati',
  '["vegetarian", "wheat", "ghee", "premium"]'::jsonb,
  0,
  null,
  5,
  true,
  true,
  3,
  NOW(),
  NOW()
),

-- Poori Products
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-POO-001',
  'Plain Poori',
  30.00,
  4.5,
  189,
  2,
  'Deep-fried puffed bread, crispy and golden',
  'assets/images/royalfoods/products/4.png',
  false,
  'Poori',
  '["vegetarian", "wheat", "fried", "crispy"]'::jsonb,
  0,
  null,
  8,
  true,
  true,
  4,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-POO-002',
  'Masala Poori',
  35.00,
  4.6,
  267,
  2,
  'Spiced poori with aromatic Indian spices',
  'assets/images/royalfoods/products/5.png',
  false,
  'Poori',
  '["vegetarian", "wheat", "spicy", "fried"]'::jsonb,
  0,
  null,
  8,
  true,
  false,
  5,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-POO-003',
  'Kashmiri Poori',
  40.00,
  4.7,
  178,
  2,
  'Special Kashmiri style poori with unique taste',
  'assets/images/royalfoods/products/6.png',
  false,
  'Poori',
  '["vegetarian", "wheat", "kashmiri", "special"]'::jsonb,
  10,
  44.00,
  10,
  true,
  true,
  6,
  NOW(),
  NOW()
),

-- Pulka Products
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PUL-001',
  'Plain Pulka',
  12.00,
  4.5,
  298,
  1,
  'Thin unleavened flatbread, light and healthy',
  'assets/images/royalfoods/products/7.png',
  false,
  'Pulka',
  '["vegetarian", "wheat", "healthy", "light"]'::jsonb,
  0,
  null,
  4,
  true,
  true,
  7,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PUL-002',
  'Ghee Pulka',
  18.00,
  4.7,
  412,
  1,
  'Soft pulka with a touch of pure ghee',
  'assets/images/royalfoods/products/8.png',
  false,
  'Pulka',
  '["vegetarian", "wheat", "ghee", "popular"]'::jsonb,
  0,
  null,
  4,
  true,
  true,
  8,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PUL-003',
  'Jowar Pulka',
  20.00,
  4.6,
  167,
  1,
  'Healthy sorghum flour pulka, gluten-free option',
  'assets/images/royalfoods/products/9.png',
  false,
  'Pulka',
  '["vegetarian", "jowar", "healthy", "gluten-free"]'::jsonb,
  0,
  null,
  5,
  true,
  false,
  9,
  NOW(),
  NOW()
),

-- Parota Products
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PAR-001',
  'Plain Parota',
  35.00,
  4.7,
  523,
  1,
  'Layered flatbread, flaky and delicious',
  'assets/images/royalfoods/products/10.png',
  false,
  'Parota',
  '["vegetarian", "layered", "flaky", "popular"]'::jsonb,
  0,
  null,
  10,
  true,
  true,
  10,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PAR-002',
  'Malabar Parota',
  40.00,
  4.8,
  678,
  1,
  'Kerala style multi-layered parota, crispy and soft',
  'assets/images/royalfoods/products/11.png',
  false,
  'Parota',
  '["vegetarian", "kerala-style", "layered", "signature"]'::jsonb,
  10,
  44.00,
  12,
  true,
  true,
  11,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PAR-003',
  'Coin Parota',
  45.00,
  4.8,
  445,
  1,
  'Small bite-sized parotas, perfect for sides',
  'assets/images/royalfoods/products/12.png',
  false,
  'Parota',
  '["vegetarian", "bite-sized", "layered", "unique"]'::jsonb,
  0,
  null,
  12,
  true,
  true,
  12,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PAR-004',
  'Wheat Parota',
  38.00,
  4.6,
  289,
  1,
  'Whole wheat parota, healthier alternative',
  'assets/images/royalfoods/products/13.png',
  false,
  'Parota',
  '["vegetarian", "wheat", "healthy", "layered"]'::jsonb,
  0,
  null,
  10,
  true,
  false,
  13,
  NOW(),
  NOW()
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'royalfoods'),
  'RF-PAR-005',
  'Cheese Parota',
  55.00,
  4.9,
  567,
  1,
  'Parota stuffed with melted cheese',
  'assets/images/royalfoods/products/14.png',
  true,
  'Parota',
  '["vegetarian", "cheese", "stuffed", "premium"]'::jsonb,
  0,
  null,
  15,
  true,
  true,
  14,
  NOW(),
  NOW()
);

-- Verify the products insertion
SELECT 
  p.name,
  p.sku,
  p.category,
  p.price,
  p.rating,
  p.is_available,
  p.is_featured
FROM products p
WHERE p.megha_store_id = (SELECT id FROM megha_stores WHERE store_code = 'royalfoods')
ORDER BY p.sort_order;

-- Count products by category
SELECT 
  p.category,
  COUNT(*) as product_count,
  AVG(p.price) as avg_price,
  MIN(p.price) as min_price,
  MAX(p.price) as max_price
FROM products p
WHERE p.megha_store_id = (SELECT id FROM megha_stores WHERE store_code = 'royalfoods')
GROUP BY p.category
ORDER BY p.category;

-- Summary statistics
SELECT 
  COUNT(*) as total_products,
  AVG(price) as avg_price,
  MIN(price) as min_price,
  MAX(price) as max_price,
  SUM(CASE WHEN is_featured THEN 1 ELSE 0 END) as featured_count
FROM products
WHERE megha_store_id = (SELECT id FROM megha_stores WHERE store_code = 'royalfoods');
