-- ============================================
-- PAWS NEXUS STORE SETUP
-- Pet care store with specialized services
-- ============================================

-- Insert Paws Nexus store
INSERT INTO megha_stores (
  store_code,
  store_name,
  store_type,
  domain,
  theme_config,
  business_hours,
  contact_email,
  support_phone,
  description,
  address,
  city,
  state,
  postal_code,
  country,
  features,
  social_links,
  settings,
  is_active,
  is_verified,
  enable_products,
  enable_cart,
  enable_payments,
  enable_inventory,
  enable_invoices,
  enable_customers,
  enable_reports
) VALUES (
  'paws-nexus',
  'Paws Nexus',
  'petcare',
  'paws-nexus.com',
  '{
    "primaryColor": "#0891b2",
    "secondaryColor": "#06b6d4", 
    "accentColor": "#14b8a6",
    "warningColor": "#f59e0b",
    "dangerColor": "#dc2626",
    "backgroundColor": "#f0fdfa",
    "surfaceColor": "#ffffff",
    "textPrimary": "#1f2937",
    "textSecondary": "#6b7280",
    "fontFamily": "Inter, sans-serif",
    "logo": "assets/images/paws-nexus/logo.png",
    "layout": "layout-pet-care"
  }',
  '{
    "monday": {"open": "09:00", "close": "18:00"},
    "tuesday": {"open": "09:00", "close": "18:00"},
    "wednesday": {"open": "09:00", "close": "18:00"},
    "thursday": {"open": "09:00", "close": "18:00"},
    "friday": {"open": "09:00", "close": "18:00"},
    "saturday": {"open": "09:00", "close": "14:00"},
    "sunday": {"open": "10:00", "close": "16:00"}
  }',
  'info@paws-nexus.com',
  '8550046444',
  'Professional pet care services including vaccinations, grooming, emergency care, and home visits for dogs and other pets.',
  '123 Pet Care Street, Veterinary District',
  'Mumbai',
  'Maharashtra',
  '400001',
  'India',
  '{
    "inventory": true,
    "delivery": true,
    "multiStore": false,
    "userRoles": true,
    "payment": true,
    "analytics": true,
    "loyaltyProgram": false,
    "appointments": true,
    "homeVisits": true,
    "emergencyServices": true
  }',
  '{
    "facebook": "https://facebook.com/paws-nexus",
    "instagram": "https://instagram.com/@paws_nexus",
    "twitter": "https://twitter.com/paws_nexus",
    "linkedin": "https://linkedin.com/company/paws-nexus",
    "youtube": "https://youtube.com/@paws_nexus"
  }',
  '{
    "appointmentBooking": true,
    "homeVisitRadius": 10,
    "emergencyResponse": true,
    "petProfiles": true,
    "vaccinationReminders": true,
    "medicationTracking": true
  }',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
);

-- Insert store location for Paws Nexus
INSERT INTO store_locations (
  megha_store_id,
  location_code,
  name,
  address,
  phone,
  hours,
  latitude,
  longitude,
  is_flagship,
  delivery_radius_km,
  min_order_amount,
  has_parking,
  has_wifi,
  has_drive_through,
  capacity,
  manager_contact,
  is_active
) VALUES (
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  'main',
  'Paws Nexus Main Clinic',
  '123 Pet Care Street, Veterinary District, Mumbai - 400001',
  '8550046444',
  'Mon-Fri: 9:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM, Sun: 10:00 AM - 4:00 PM',
  19.0760,
  72.8777,
  true,
  15.0,
  0.00,
  true,
  true,
  false,
  50,
  'Dr. Sarah Johnson',
  true
);

-- Insert categories for pet care
INSERT INTO categories (
  name,
  description,
  slug,
  megha_store_id,
  parent_id,
  sort_order,
  is_active,
  image_url
) VALUES 
(
  'Pet Care Services',
  'Professional pet care and medical services',
  'pet-care-services',
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  NULL,
  1,
  true,
  'assets/images/paws-nexus/categories/pet-care.jpg'
),
(
  'Dogs',
  'Services specifically for dogs',
  'dogs',
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  (SELECT id FROM categories WHERE slug = 'pet-care-services' AND megha_store_id = (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus')),
  1,
  true,
  'assets/images/paws-nexus/categories/dogs.jpg'
),
(
  'Cats',
  'Services specifically for cats',
  'cats',
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  (SELECT id FROM categories WHERE slug = 'pet-care-services' AND megha_store_id = (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus')),
  2,
  true,
  'assets/images/paws-nexus/categories/cats.jpg'
),
(
  'Emergency Care',
  '24/7 emergency pet care services',
  'emergency-care',
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  (SELECT id FROM categories WHERE slug = 'pet-care-services' AND megha_store_id = (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus')),
  3,
  true,
  'assets/images/paws-nexus/categories/emergency.jpg'
);

-- Insert sample freelance doctors
INSERT INTO freelance_doctors (
  megha_store_id,
  doctor_code,
  full_name,
  specialization,
  qualifications,
  experience_years,
  phone,
  email,
  address,
  city,
  state,
  pincode,
  consultation_fee,
  home_visit_fee,
  emergency_fee,
  available_days,
  available_hours,
  is_available_for_home_visits,
  is_available_for_emergency,
  rating,
  review_count,
  is_verified,
  is_active
) VALUES (
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  'DR001',
  'Dr. Sarah Johnson',
  'veterinary',
  'BVSc, MVSc in Veterinary Medicine, 8 years experience',
  8,
  '8550046444',
  'sarah.johnson@paws-nexus.com',
  '123 Pet Care Street, Veterinary District',
  'Mumbai',
  'Maharashtra',
  '400001',
  500.00,
  200.00,
  1000.00,
  '{"monday": true, "tuesday": true, "wednesday": true, "thursday": true, "friday": true, "saturday": true, "sunday": true}',
  '{"start": "09:00", "end": "18:00"}',
  true,
  true,
  4.8,
  150,
  true,
  true
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  'DR002',
  'Dr. Michael Chen',
  'veterinary',
  'DVM, PhD in Animal Health, 12 years experience',
  12,
  '8550046445',
  'michael.chen@paws-nexus.com',
  '456 Animal Hospital Road',
  'Mumbai',
  'Maharashtra',
  '400002',
  600.00,
  250.00,
  1200.00,
  '{"monday": true, "tuesday": true, "wednesday": true, "thursday": true, "friday": true, "saturday": false, "sunday": false}',
  '{"start": "08:00", "end": "17:00"}',
  true,
  true,
  4.9,
  200,
  true,
  true
);

-- Insert sample pet stores (partners)
INSERT INTO pet_stores (
  megha_store_id,
  store_code,
  store_name,
  store_type,
  contact_person,
  phone,
  email,
  address,
  city,
  state,
  pincode,
  latitude,
  longitude,
  business_hours,
  delivery_radius_km,
  min_order_amount,
  is_partner,
  is_active
) VALUES (
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  'PETSUPPLIES001',
  'Pet Paradise Supplies',
  'pet_supplies',
  'John Smith',
  '8550046500',
  'info@petparadise.com',
  '789 Pet Supplies Lane, Mumbai',
  'Mumbai',
  'Maharashtra',
  '400003',
  19.0760,
  72.8777,
  '{"monday": {"open": "09:00", "close": "19:00"}, "tuesday": {"open": "09:00", "close": "19:00"}, "wednesday": {"open": "09:00", "close": "19:00"}, "thursday": {"open": "09:00", "close": "19:00"}, "friday": {"open": "09:00", "close": "19:00"}, "saturday": {"open": "09:00", "close": "18:00"}, "sunday": {"open": "10:00", "close": "17:00"}}',
  10.0,
  500.00,
  true,
  true
),
(
  (SELECT id FROM megha_stores WHERE store_code = 'paws-nexus'),
  'PETMEDICINE001',
  'VetMed Pharmacy',
  'pet_medicine',
  'Dr. Lisa Wilson',
  '8550046501',
  'pharmacy@vetmed.com',
  '321 Medicine Street, Mumbai',
  'Mumbai',
  'Maharashtra',
  '400004',
  19.0760,
  72.8777,
  '{"monday": {"open": "08:00", "close": "20:00"}, "tuesday": {"open": "08:00", "close": "20:00"}, "wednesday": {"open": "08:00", "close": "20:00"}, "thursday": {"open": "08:00", "close": "20:00"}, "friday": {"open": "08:00", "close": "20:00"}, "saturday": {"open": "08:00", "close": "18:00"}, "sunday": {"open": "09:00", "close": "17:00"}}',
  15.0,
  200.00,
  true,
  true
);

-- Verify the setup
SELECT 
  s.store_code,
  s.store_name,
  s.store_type,
  s.support_phone,
  s.is_active,
  l.name as location_name,
  l.phone as location_phone
FROM megha_stores s
LEFT JOIN store_locations l ON s.id = l.megha_store_id
WHERE s.store_code = 'paws-nexus';
