-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.cancellation_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  time_limit_minutes integer,
  refund_percentage numeric,
  cancellation_fee numeric DEFAULT 0.00,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cancellation_policies_pkey PRIMARY KEY (id),
  CONSTRAINT cancellation_policies_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  user_id uuid,
  product_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  customizations jsonb,
  special_instructions text,
  unit_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  slug character varying NOT NULL,
  megha_store_id uuid NOT NULL,
  parent_id uuid,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.customer_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  address_type character varying CHECK (address_type::text = ANY (ARRAY['home'::character varying, 'work'::character varying, 'other'::character varying]::text[])),
  full_address text NOT NULL,
  landmark text,
  city character varying,
  state character varying,
  pincode character varying,
  latitude numeric,
  longitude numeric,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT customer_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.delivery_partners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  user_id uuid,
  partner_code character varying,
  vehicle_type character varying CHECK (vehicle_type::text = ANY (ARRAY['bike'::character varying, 'car'::character varying, 'cycle'::character varying, 'van'::character varying]::text[])),
  license_number character varying,
  phone character varying,
  emergency_contact character varying,
  is_available boolean DEFAULT true,
  current_location_lat numeric,
  current_location_lng numeric,
  max_orders_capacity integer DEFAULT 3,
  current_orders_count integer DEFAULT 0,
  rating numeric DEFAULT 0.0,
  total_deliveries integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_partners_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_partners_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id),
  CONSTRAINT delivery_partners_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.delivery_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  delivery_partner_id uuid,
  status character varying CHECK (status::text = ANY (ARRAY['assigned'::character varying, 'picked_up'::character varying, 'in_transit'::character varying, 'reached_destination'::character varying, 'delivered'::character varying, 'failed'::character varying, 'returned'::character varying]::text[])),
  pickup_time timestamp with time zone,
  estimated_delivery_time timestamp with time zone,
  actual_delivery_time timestamp with time zone,
  delivery_location_lat numeric,
  delivery_location_lng numeric,
  delivery_notes text,
  customer_signature jsonb,
  delivery_photo_url character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_tracking_delivery_partner_id_fkey FOREIGN KEY (delivery_partner_id) REFERENCES public.delivery_partners(id),
  CONSTRAINT delivery_tracking_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.location_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_location_id uuid,
  product_id uuid,
  stock_quantity integer NOT NULL DEFAULT 0,
  reserved_quantity integer DEFAULT 0,
  low_stock_threshold integer DEFAULT 5,
  max_stock_capacity integer DEFAULT 1000,
  cost_price numeric,
  last_restocked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT location_inventory_store_location_id_fkey FOREIGN KEY (store_location_id) REFERENCES public.store_locations(id),
  CONSTRAINT location_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.location_staff (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_location_id uuid,
  user_id uuid,
  employee_id character varying,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['location_manager'::character varying, 'assistant_manager'::character varying, 'barista'::character varying, 'cashier'::character varying, 'kitchen_staff'::character varying, 'delivery_person'::character varying, 'cleaner'::character varying]::text[])),
  shift_schedule jsonb,
  hourly_rate numeric,
  hire_date date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_staff_pkey PRIMARY KEY (id),
  CONSTRAINT location_staff_store_location_id_fkey FOREIGN KEY (store_location_id) REFERENCES public.store_locations(id),
  CONSTRAINT location_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.megha_stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_code character varying NOT NULL UNIQUE,
  store_name character varying NOT NULL,
  store_type character varying NOT NULL,
  domain character varying,
  theme_config jsonb,
  business_hours jsonb,
  contact_email character varying,
  support_phone character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT megha_stores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  template_type character varying,
  channel character varying CHECK (channel::text = ANY (ARRAY['sms'::character varying, 'email'::character varying, 'push'::character varying, 'whatsapp'::character varying]::text[])),
  subject character varying,
  content text,
  variables jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  order_id uuid,
  megha_store_id uuid,
  type character varying CHECK (type::text = ANY (ARRAY['order_confirmed'::character varying, 'preparing'::character varying, 'ready'::character varying, 'out_for_delivery'::character varying, 'delivered'::character varying, 'cancelled'::character varying, 'refunded'::character varying, 'promotion'::character varying]::text[])),
  title character varying,
  message text,
  data jsonb,
  is_read boolean DEFAULT false,
  sent_via character varying CHECK (sent_via::text = ANY (ARRAY['push'::character varying, 'sms'::character varying, 'email'::character varying, 'in_app'::character varying]::text[])),
  sent_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT notifications_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  customizations jsonb,
  special_instructions text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  from_status character varying,
  to_status character varying,
  changed_by uuid,
  change_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying UNIQUE,
  megha_store_id uuid,
  user_id uuid,
  store_location_id uuid,
  pickup_location_id uuid,
  customer_address_id uuid,
  order_type character varying DEFAULT 'delivery'::character varying CHECK (order_type::text = ANY (ARRAY['delivery'::character varying, 'pickup'::character varying, 'dine_in'::character varying]::text[])),
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0.00,
  delivery_fee numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  total_amount numeric NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'preparing'::character varying, 'ready'::character varying, 'out_for_delivery'::character varying, 'delivered'::character varying, 'cancelled'::character varying, 'refunded'::character varying]::text[])),
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  payment_method character varying,
  payment_id character varying,
  delivery_address jsonb,
  billing_address jsonb,
  phone_number character varying,
  customer_notes text,
  staff_notes text,
  estimated_preparation_time integer,
  actual_preparation_time integer,
  estimated_delivery_time timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_reason text,
  refund_amount numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT orders_store_location_id_fkey FOREIGN KEY (store_location_id) REFERENCES public.store_locations(id),
  CONSTRAINT orders_pickup_location_id_fkey FOREIGN KEY (pickup_location_id) REFERENCES public.store_locations(id),
  CONSTRAINT orders_customer_address_id_fkey FOREIGN KEY (customer_address_id) REFERENCES public.customer_addresses(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  payment_gateway character varying CHECK (payment_gateway::text = ANY (ARRAY['razorpay'::character varying, 'stripe'::character varying, 'paytm'::character varying, 'phonepe'::character varying, 'gpay'::character varying, 'cash'::character varying]::text[])),
  transaction_id character varying,
  gateway_order_id character varying,
  amount numeric,
  currency character varying DEFAULT 'INR'::character varying,
  status character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'success'::character varying, 'failed'::character varying, 'refunded'::character varying, 'cancelled'::character varying]::text[])),
  gateway_response jsonb,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  sku character varying,
  name character varying NOT NULL,
  price numeric NOT NULL,
  rating numeric DEFAULT 0.0,
  review_count integer DEFAULT 0,
  serves integer DEFAULT 1,
  description text,
  image_url character varying,
  gallery_images jsonb,
  customisable boolean DEFAULT false,
  customization_options jsonb,
  category character varying,
  tags jsonb,
  discount_percentage integer DEFAULT 0,
  old_price numeric,
  nutritional_info jsonb,
  allergen_info jsonb,
  preparation_time integer,
  is_available boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);
CREATE TABLE public.promotions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  promo_code character varying,
  title character varying NOT NULL,
  description text,
  discount_type character varying CHECK (discount_type::text = ANY (ARRAY['percentage'::character varying, 'fixed_amount'::character varying, 'buy_x_get_y'::character varying]::text[])),
  discount_value numeric,
  min_order_amount numeric,
  max_discount_amount numeric,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  applicable_products jsonb,
  applicable_categories jsonb,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promotions_pkey PRIMARY KEY (id),
  CONSTRAINT promotions_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);
CREATE TABLE public.refunds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  payment_transaction_id uuid,
  refund_amount numeric,
  refund_reason text,
  status character varying CHECK (status::text = ANY (ARRAY['initiated'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  gateway_refund_id character varying,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT refunds_pkey PRIMARY KEY (id),
  CONSTRAINT refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT refunds_payment_transaction_id_fkey FOREIGN KEY (payment_transaction_id) REFERENCES public.payment_transactions(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  user_id uuid,
  product_id uuid,
  order_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  is_verified boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id),
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.store_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  location_code character varying,
  name character varying NOT NULL,
  address text NOT NULL,
  phone character varying NOT NULL,
  hours text NOT NULL,
  latitude numeric,
  longitude numeric,
  is_flagship boolean DEFAULT false,
  delivery_radius_km numeric DEFAULT 10.0,
  min_order_amount numeric DEFAULT 0.00,
  has_parking boolean DEFAULT false,
  has_wifi boolean DEFAULT false,
  has_drive_through boolean DEFAULT false,
  capacity integer,
  manager_contact character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT store_locations_pkey PRIMARY KEY (id),
  CONSTRAINT store_locations_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);
CREATE TABLE public.tax_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  megha_store_id uuid,
  state character varying,
  tax_type character varying CHECK (tax_type::text = ANY (ARRAY['GST'::character varying, 'VAT'::character varying, 'Service_Tax'::character varying, 'CGST'::character varying, 'SGST'::character varying, 'IGST'::character varying]::text[])),
  rate numeric,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tax_rates_pkey PRIMARY KEY (id),
  CONSTRAINT tax_rates_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);
CREATE TABLE public.tekmegha_all_clients (
  client_name text,
  Product_Type text,
  Product_Details text,
  Expiry_Date date,
  tm_billing_month bigint,
  website text,
  tekmegha_client_id bigint,
  Provider text,
  ID bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT tekmegha_all_clients_pkey PRIMARY KEY (ID)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  megha_store_id uuid,
  role_name character varying NOT NULL CHECK (role_name::text = ANY (ARRAY['admin'::character varying, 'manager'::character varying, 'inventory_manager'::character varying, 'super_admin'::character varying, 'store_manager'::character varying, 'employee'::character varying, 'customer'::character varying]::text[])),
  permissions jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_megha_store_id_fkey FOREIGN KEY (megha_store_id) REFERENCES public.megha_stores(id)
);